# Generated by Django 4.1.3 on 2022-11-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RusticalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interes',
            name='status',
            field=models.CharField(choices=[(0, 'Me interesa adquirir Orellanas'), (1, 'Me interesa cultivar Orellanas')], default=0, max_length=32),
        ),
    ]
