# Generated by Django 4.1.3 on 2022-11-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RusticalApp', '0002_alter_interes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interes',
            name='status',
            field=models.CharField(choices=[('Compra', 'Me interesa adquirir Orellanas'), ('Cultivo', 'Me interesa cultivar Orellanas')], max_length=32),
        ),
    ]
