# Generated by Django 4.1.3 on 2022-11-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RusticalApp', '0003_alter_interes_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compra',
            new_name='compra1',
        ),
        migrations.RenameModel(
            old_name='Interes',
            new_name='Interes1',
        ),
        migrations.RenameModel(
            old_name='usuario',
            new_name='usuario1',
        ),
    ]
