# Generated by Django 4.1.3 on 2022-12-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RusticalApp', '0004_rename_compra_compra1_rename_interes_interes1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra1',
            name='Peso',
            field=models.IntegerField(),
        ),
    ]
