# Generated by Django 4.1.3 on 2022-12-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RusticalApp', '0005_alter_compra1_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interes1',
            name='status',
        ),
        migrations.AddField(
            model_name='interes1',
            name='opcion',
            field=models.CharField(choices=[('Compra', 'Me interesa adquirir Orellanas'), ('Cultivo', 'Me interesa cultivar Orellanas')], default='Hola', max_length=40),
        ),
    ]
